// Code generated by protoc-gen-go. DO NOT EDIT.
// source: math.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RectArgs struct {
	Width                float64  `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               float64  `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RectArgs) Reset()         { *m = RectArgs{} }
func (m *RectArgs) String() string { return proto.CompactTextString(m) }
func (*RectArgs) ProtoMessage()    {}
func (*RectArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_math_ea3b7164c0717b48, []int{0}
}
func (m *RectArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RectArgs.Unmarshal(m, b)
}
func (m *RectArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RectArgs.Marshal(b, m, deterministic)
}
func (dst *RectArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RectArgs.Merge(dst, src)
}
func (m *RectArgs) XXX_Size() int {
	return xxx_messageInfo_RectArgs.Size(m)
}
func (m *RectArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RectArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RectArgs proto.InternalMessageInfo

func (m *RectArgs) GetWidth() float64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *RectArgs) GetHeight() float64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type RectReply struct {
	Perimeter            float64  `protobuf:"fixed64,1,opt,name=perimeter,proto3" json:"perimeter,omitempty"`
	Square               float64  `protobuf:"fixed64,2,opt,name=square,proto3" json:"square,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RectReply) Reset()         { *m = RectReply{} }
func (m *RectReply) String() string { return proto.CompactTextString(m) }
func (*RectReply) ProtoMessage()    {}
func (*RectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_math_ea3b7164c0717b48, []int{1}
}
func (m *RectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RectReply.Unmarshal(m, b)
}
func (m *RectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RectReply.Marshal(b, m, deterministic)
}
func (dst *RectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RectReply.Merge(dst, src)
}
func (m *RectReply) XXX_Size() int {
	return xxx_messageInfo_RectReply.Size(m)
}
func (m *RectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RectReply.DiscardUnknown(m)
}

var xxx_messageInfo_RectReply proto.InternalMessageInfo

func (m *RectReply) GetPerimeter() float64 {
	if m != nil {
		return m.Perimeter
	}
	return 0
}

func (m *RectReply) GetSquare() float64 {
	if m != nil {
		return m.Square
	}
	return 0
}

type CircleArgs struct {
	Radius               float64  `protobuf:"fixed64,1,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CircleArgs) Reset()         { *m = CircleArgs{} }
func (m *CircleArgs) String() string { return proto.CompactTextString(m) }
func (*CircleArgs) ProtoMessage()    {}
func (*CircleArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_math_ea3b7164c0717b48, []int{2}
}
func (m *CircleArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircleArgs.Unmarshal(m, b)
}
func (m *CircleArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircleArgs.Marshal(b, m, deterministic)
}
func (dst *CircleArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircleArgs.Merge(dst, src)
}
func (m *CircleArgs) XXX_Size() int {
	return xxx_messageInfo_CircleArgs.Size(m)
}
func (m *CircleArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_CircleArgs.DiscardUnknown(m)
}

var xxx_messageInfo_CircleArgs proto.InternalMessageInfo

func (m *CircleArgs) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type CircleReply struct {
	Length               float64  `protobuf:"fixed64,1,opt,name=length,proto3" json:"length,omitempty"`
	Square               float64  `protobuf:"fixed64,2,opt,name=square,proto3" json:"square,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CircleReply) Reset()         { *m = CircleReply{} }
func (m *CircleReply) String() string { return proto.CompactTextString(m) }
func (*CircleReply) ProtoMessage()    {}
func (*CircleReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_math_ea3b7164c0717b48, []int{3}
}
func (m *CircleReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircleReply.Unmarshal(m, b)
}
func (m *CircleReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircleReply.Marshal(b, m, deterministic)
}
func (dst *CircleReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircleReply.Merge(dst, src)
}
func (m *CircleReply) XXX_Size() int {
	return xxx_messageInfo_CircleReply.Size(m)
}
func (m *CircleReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CircleReply.DiscardUnknown(m)
}

var xxx_messageInfo_CircleReply proto.InternalMessageInfo

func (m *CircleReply) GetLength() float64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *CircleReply) GetSquare() float64 {
	if m != nil {
		return m.Square
	}
	return 0
}

func init() {
	proto.RegisterType((*RectArgs)(nil), "rpc.RectArgs")
	proto.RegisterType((*RectReply)(nil), "rpc.RectReply")
	proto.RegisterType((*CircleArgs)(nil), "rpc.CircleArgs")
	proto.RegisterType((*CircleReply)(nil), "rpc.CircleReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MathClient is the client API for Math service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MathClient interface {
	Rect(ctx context.Context, in *RectArgs, opts ...grpc.CallOption) (*RectReply, error)
	Circle(ctx context.Context, in *CircleArgs, opts ...grpc.CallOption) (*CircleReply, error)
}

type mathClient struct {
	cc *grpc.ClientConn
}

func NewMathClient(cc *grpc.ClientConn) MathClient {
	return &mathClient{cc}
}

func (c *mathClient) Rect(ctx context.Context, in *RectArgs, opts ...grpc.CallOption) (*RectReply, error) {
	out := new(RectReply)
	err := c.cc.Invoke(ctx, "/rpc.Math/Rect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathClient) Circle(ctx context.Context, in *CircleArgs, opts ...grpc.CallOption) (*CircleReply, error) {
	out := new(CircleReply)
	err := c.cc.Invoke(ctx, "/rpc.Math/Circle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathServer is the server API for Math service.
type MathServer interface {
	Rect(context.Context, *RectArgs) (*RectReply, error)
	Circle(context.Context, *CircleArgs) (*CircleReply, error)
}

func RegisterMathServer(s *grpc.Server, srv MathServer) {
	s.RegisterService(&_Math_serviceDesc, srv)
}

func _Math_Rect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RectArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServer).Rect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Math/Rect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServer).Rect(ctx, req.(*RectArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Math_Circle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CircleArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServer).Circle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Math/Circle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServer).Circle(ctx, req.(*CircleArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Math_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Math",
	HandlerType: (*MathServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rect",
			Handler:    _Math_Rect_Handler,
		},
		{
			MethodName: "Circle",
			Handler:    _Math_Circle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "math.proto",
}

func init() { proto.RegisterFile("math.proto", fileDescriptor_math_ea3b7164c0717b48) }

var fileDescriptor_math_ea3b7164c0717b48 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xad, 0xae, 0xc1, 0x1d, 0xf1, 0x0f, 0x83, 0x94, 0x65, 0xf1, 0x20, 0x41, 0xd0, 0x8b,
	0x3d, 0xe8, 0xc5, 0x8b, 0x87, 0xe2, 0xd9, 0x4b, 0x3f, 0x80, 0x10, 0xd3, 0xa1, 0x09, 0xb4, 0x36,
	0x4e, 0x53, 0xc4, 0x6f, 0x2f, 0x4d, 0xd2, 0xd6, 0x8b, 0xc7, 0xdf, 0xcb, 0xcc, 0x7b, 0x2f, 0x03,
	0xd0, 0x29, 0x6f, 0x0a, 0xc7, 0xbd, 0xef, 0xf1, 0x88, 0x9d, 0x96, 0xcf, 0x70, 0x52, 0x91, 0xf6,
	0x25, 0x37, 0x03, 0x5e, 0xc1, 0xf1, 0xb7, 0xad, 0xbd, 0xd9, 0x65, 0x37, 0xd9, 0x7d, 0x56, 0x45,
	0xc0, 0x1c, 0x84, 0x21, 0xdb, 0x18, 0xbf, 0x3b, 0x0c, 0x72, 0x22, 0x59, 0xc2, 0x76, 0xda, 0xac,
	0xc8, 0xb5, 0x3f, 0x78, 0x0d, 0x5b, 0x47, 0x6c, 0x3b, 0xf2, 0xc4, 0x69, 0x7d, 0x15, 0x26, 0x8b,
	0xe1, 0x6b, 0x54, 0x4c, 0xb3, 0x45, 0x24, 0x79, 0x0b, 0xf0, 0x6a, 0x59, 0xb7, 0x14, 0xe2, 0x73,
	0x10, 0xac, 0x6a, 0x3b, 0x0e, 0xc9, 0x20, 0x91, 0x7c, 0x81, 0xd3, 0x38, 0x15, 0xa3, 0x72, 0x10,
	0x2d, 0x7d, 0x36, 0x4b, 0xcd, 0x44, 0xff, 0x85, 0x3c, 0xbe, 0xc3, 0xe6, 0x4d, 0x79, 0x83, 0x77,
	0xb0, 0x99, 0xfa, 0xe2, 0x59, 0xc1, 0x4e, 0x17, 0xf3, 0xa7, 0xf7, 0xe7, 0x0b, 0x06, 0x7b, 0x79,
	0x80, 0x0f, 0x20, 0x62, 0x1e, 0x5e, 0x84, 0xb7, 0xb5, 0xe2, 0xfe, 0xf2, 0x8f, 0x90, 0xc6, 0x3f,
	0x44, 0xb8, 0xe6, 0xd3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x15, 0x2a, 0x13, 0x5b, 0x01,
	0x00, 0x00,
}
